export const API_ROUTES = {
    DOCTOR_REGISTRATION: '/doctor/register',
    DOCTOR_LOGIN: '/doctor/login',
    DOCTOR_AVAILABILITY: '/doctor/availability',
    DOCTOR_APPOINTMENTS: '/doctor/appointments',
    DOCTOR_SLOTS: '/doctor/slots',
    ALL_DOCTORS: '/doctor/allDoctors',
    PATIENT_REGISTRATION: '/patient/register',
    PATIENT_LOGIN: '/patient/login',
    PATIENT_CLOSEST_NGO: '/patient/findClosestNgos',
    PATIENT_BEST_DOCTOR: '/patient/bestPossibleDoctors',
    PATIENT_SELECT_DOCTOR: '/patient/selectYourDoctor',
    PATIENT_APPOINTMENTS: '/patient/appointments',
    CREATE_APPOINTMENT: '/appointment/addAppointment',
};